name = "ELF2"
uuid = "bf897294-8cb0-4da4-9eaa-611f3b2618fb"
authors = ["akawashiro <a.kawashiro@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
